CREATE TABLE OCO.OCO30100 (
  ANNCE_NO bigint NOT NULL AUTO_INCREMENT COMMENT '공지번호',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  ANNCE_TITLE_NM varchar(100) DEFAULT NULL COMMENT '공지제목명',
  ANNCE_CNTNT longtext COMMENT '공지내용',
  ANNCE_TASK_CL_CD varchar(2) DEFAULT NULL COMMENT '공지업무구분코드',
  ANNCE_CTGR_CL_CD varchar(2) DEFAULT NULL COMMENT '공지카테고리구분코드',
  ANNCE_START_DTM varchar(14) DEFAULT NULL COMMENT '공지시작일시',
  ANNCE_END_DTM varchar(14) DEFAULT NULL COMMENT '공지종료일시',
  SUPER_ANNCE_START_DTM varchar(14) DEFAULT NULL COMMENT '상위공지시작일시',
  SUPER_ANNCE_END_DTM varchar(14) DEFAULT NULL COMMENT '상위공지종료일시',
  REG_USERID varchar(10) DEFAULT NULL COMMENT '등록사용자ID',
  REG_DTMD datetime DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시D',
  DEL_YN varchar(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  PRIMARY KEY (ANNCE_NO)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT='공통_공지내역';

CREATE TABLE OCO.OCO30101 (
  ANNCE_NO bigint NOT NULL COMMENT '공지번호',
  USERID varchar(10) NOT NULL COMMENT '사용자ID',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  PRIMARY KEY (ANNCE_NO,USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_공지조회이력';


CREATE TABLE OCO.OCO30102 (
  ANNCE_NO bigint NOT NULL COMMENT '공지번호',
  ANNCE_OBJ_SEQ int NOT NULL COMMENT '공지대상순번',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  ANNCE_OBJ_DEPT_CL_CD varchar(2) DEFAULT NULL COMMENT '공지대상부서구분코드',
  ANNCE_OBJ_DEPT_TEAM_CD varchar(6) DEFAULT NULL COMMENT '공지대상부서팀코드',
  PRIMARY KEY (ANNCE_NO,ANNCE_OBJ_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_공지대상목록';

CREATE TABLE OCO.OCO30110 (
  ANNCE_NO bigint NOT NULL COMMENT '공지번호',
  ATAC_FILE_NO bigint NOT NULL DEFAULT '0' COMMENT '첨부파일번호',
  LAST_CHNGR_ID varchar(10) NOT NULL COMMENT '최종변경자ID',
  LAST_CHNG_DTMD datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종변경일시D',
  DEL_YN varchar(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  PRIMARY KEY (ANNCE_NO,ATAC_FILE_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통_공지첨부파일목록';