
CREATE DATABASE OIF;

CREATE USER 'com_dev'@'%' IDENTIFIED BY 'qwer1234!';

-- 권한 부여
GRANT ALL PRIVILEGES ON OIF.* TO 'com_dev'@'%';
FLUSH PRIVILEGES;

CREATE TABLE OIF.OIF21300 (
    BSSMACD VARCHAR(2) NOT NULL,
    BSS_HQ_NM VARCHAR(50) NOT NULL,
    USE_YN VARCHAR(1) NOT NULL,
    CREATED_BY VARCHAR(255),
    CREATED_AT TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_AT TIMESTAMP,
    PRIMARY KEY (BSSMACD)
) ENGINE=InnoDB;

CREATE TABLE OIF.OIF21200 (
    DEPTCD VARCHAR(8) NOT NULL,
    MGMT_DEPTCD VARCHAR(6),
    DEPT_NM VARCHAR(50),
    ENGSH_DEPT_NM VARCHAR(50),
    ENGSH_DEPT_ABBR_NM VARCHAR(50),
    BSSMACD VARCHAR(2),
    SUPER_DEPTCD VARCHAR(6),
    DEPT_GRADE_CD VARCHAR(1),
    DEPT_CRAT_DT VARCHAR(8),
    DEPT_ABOL_DT VARCHAR(8),
    FEMP_DEPTCD VARCHAR(6),
    WHTAX_BZPL_CD VARCHAR(6),
    SALS_DEPTCD VARCHAR(6),
    INV_DEPTCD VARCHAR(6),
    INVNT_WRHUS_CD VARCHAR(6),
    VAT_BZPL_CD VARCHAR(6),
    ZIPCD VARCHAR(6),
    BASIC_ADDR VARCHAR(200),
    DETIL_ADDR VARCHAR(200),
    PHNO VARCHAR(14),
    FAX_NO VARCHAR(14),
    BZNO VARCHAR(10),
    BZMAN_ACQ_DT VARCHAR(8),
    TXOFC_CD VARCHAR(3),
    TXOFC_NM VARCHAR(20),
    COM_BSCND_NM VARCHAR(30),
    COM_ITM_NM VARCHAR(30),
    COM_CORP_NM VARCHAR(50),
    USE_YN VARCHAR(1),
    CCNTR_CD VARCHAR(10),
    RPRTT_NM VARCHAR(30),
    EXTSN_NO VARCHAR(4),
    CREATED_BY VARCHAR(255),
    CREATED_AT TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_AT TIMESTAMP,
    PRIMARY KEY (DEPTCD)
) ENGINE=InnoDB;

CREATE TABLE OIF.OIF21100 (
    EMPNO VARCHAR(8) NOT NULL,
    EMP_KRN_NM VARCHAR(30) NOT NULL,
    EMP_ENGLNM VARCHAR(20) NOT NULL,
    EMP_ENGFNM VARCHAR(20),
    DEPTCD VARCHAR(6),
    BTHDY VARCHAR(8),
    OWHM_PHNO VARCHAR(14),
    MPHNO VARCHAR(14),
    GROUP_ENTCP_DT VARCHAR(8),
    TCOM_ENTCP_DT VARCHAR(8),
    CURTP_OFORD_DT VARCHAR(8),
    CURTP_OFORD_CD VARCHAR(3),
    RESG_DT VARCHAR(8),
    COM_CL_CD VARCHAR(1),
    CLOFP_CD VARCHAR(3),
    REOFO_CD VARCHAR(3),
    JGP_CD VARCHAR(1),
    VCTN_CD VARCHAR(3),
    TEAMBR_CL_CD VARCHAR(3),
    CLOFP_NM VARCHAR(20),
    JGP_NM VARCHAR(20),
    VCTN_NM VARCHAR(20),
    EMAILADDR VARCHAR(100),
    BEFO_EMPNO VARCHAR(8),
    CREATED_BY VARCHAR(255),
    CREATED_AT TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_AT TIMESTAMP,
    PRIMARY KEY (EMPNO)
) ENGINE=InnoDB;
